name: Run Commands on VMs

on:
  workflow_dispatch:

jobs:
  execute-vm-commands:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run commands on VMs
      run: python scripts/run_commands.py

    - name: Upload logs to GitHub Artifacts
      if: always()  # Always run this step, even if the previous step fails
      uses: actions/upload-artifact@v4
      with:
        name: vm-logs
        path: logs/
